##########################################################
# Configuration file for analysis of beekeeper migrations. 
##########################################################

#######
# Utils
#######
hopper_url: http://172.16.34.59:8989/route  # Replace with own IP.
figure_dir: ../figures/
slovenia_shapefile: ../data/raw/shapefiles/fitogeogD96.shp

###############
# Preprocessing
###############
origins: ../data/raw/cebele_KIS_130123.xlsx
destinations: ../data/raw/cebele_KIS_premiki_130123.xlsx
migrations_processed: ../data/derived/migrations_processed.xlsx

############
# Processing
############
fuel_calibrations: ../data/derived/migrations_fuel_calibration.xlsx
survey_results: ../data/raw/migration_survey_results.xlsx
fuel_prices: ../data/meta/cene_goriv.xlsx
migrations_travel_costs: ../output/migrations_travel_costs.xlsx

# Used in jupyter notebook
distances: ../output/KMG_MID_interapiary_distances.csv
migration_stats: ../output/Migration_Stats.xlsx

#########
# Figures
#########
# Used in model_of_travel_costs.py
cost_per_hive_fig: ../figures/cost_per_hive
cost_per_hive_per_km_fig: ../figures/cost_per_hive_per_km
cost_per_honey_kg_fig: ../figures/cost_honey_kilo

# Used in migrations_fuel_calculations.py
fuel_consumption_calibration_fig: ../figures/fuel_consumption_calibration

#####################
# Migrations_stats.py
#####################
distances_traveled_fig: ../figures/traveled_distances_within_migration
yearly_costs_fig: ../figures/yearly_costs_of_colony_relocations
travel_time_fig: ../figures/traveled_time_within_migration
